"""
PDF Report Generator using ReportLab
Creates professional-looking IRS Form 8949 reports
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime


def generate_pdf_report(summary_data: dict, output_path: str):
    """
    Generate a professional PDF tax report
    
    Args:
        summary_data: Dictionary from TaxCalculator.generate_summary()
        output_path: Path to save the PDF file
    """
    
    # Create PDF document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch,
    )
    
    # Container for PDF elements
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#1a1a1a'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=12,
        spaceBefore=20,
        fontName='Helvetica-Bold'
    )
    
    normal_style = styles['Normal']
    
    # Title
    elements.append(Paragraph("Cryptocurrency Tax Report", title_style))
    elements.append(Paragraph("Form 8949 - Sales and Other Dispositions of Capital Assets", normal_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Disclaimer
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#666666'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique'
    )
    
    disclaimer_text = """
    This report is generated for informational purposes only and does not constitute tax advice.
    Please consult with a qualified tax professional before filing your taxes.
    Generated by CryptoTax Micro - cryptotaxmicro.com
    """
    elements.append(Paragraph(disclaimer_text, disclaimer_style))
    elements.append(Spacer(1, 0.3*inch))
    
    # Summary Information
    summary_data_table = [
        ['Report Date:', datetime.now().strftime('%B %d, %Y')],
        ['Cost Basis Method:', summary_data['method']],
        ['Total Transactions:', str(summary_data['total_transactions'])],
        ['Total Sales:', str(summary_data['total_sales'])],
    ]
    
    summary_table = Table(summary_data_table, colWidths=[2.5*inch, 3*inch])
    summary_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#555555')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    
    elements.append(summary_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Tax Summary Box
    tax_summary_data = [
        ['Tax Summary', ''],
        ['Short-term Capital Gain/Loss:', f"${summary_data['short_term_gain_loss']:,.2f}"],
        ['Long-term Capital Gain/Loss:', f"${summary_data['long_term_gain_loss']:,.2f}"],
        ['Total Capital Gain/Loss:', f"${summary_data['total_gain_loss']:,.2f}"],
    ]
    
    tax_summary_table = Table(tax_summary_data, colWidths=[3.5*inch, 2*inch])
    tax_summary_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 1), (1, -1), 'RIGHT'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#bdc3c7')),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#ecf0f1')),
        ('FONTNAME', (0, -1), (0, -1), 'Helvetica-Bold'),
    ]))
    
    elements.append(tax_summary_table)
    elements.append(Spacer(1, 0.4*inch))
    
    # Short-term Transactions
    if any(g['term'] == 'short-term' for g in summary_data['realized_gains']):
        elements.append(Paragraph("Short-Term Transactions (Held 1 Year or Less)", heading_style))
        
        st_data = [['Asset', 'Date Acquired', 'Date Sold', 'Proceeds', 'Cost Basis', 'Gain/Loss']]
        
        for gain in summary_data['realized_gains']:
            if gain['term'] == 'short-term':
                st_data.append([
                    gain['symbol'],
                    gain['date_acquired'].strftime('%m/%d/%Y'),
                    gain['date_sold'].strftime('%m/%d/%Y'),
                    f"${gain['proceeds']:,.2f}",
                    f"${gain['cost_basis']:,.2f}",
                    f"${gain['gain_loss']:,.2f}"
                ])
        
        st_table = Table(st_data, colWidths=[0.8*inch, 1.2*inch, 1.2*inch, 1.3*inch, 1.3*inch, 1.2*inch])
        st_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (3, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
        ]))
        
        elements.append(st_table)
        elements.append(Spacer(1, 0.3*inch))
    
    # Long-term Transactions
    if any(g['term'] == 'long-term' for g in summary_data['realized_gains']):
        elements.append(Paragraph("Long-Term Transactions (Held More Than 1 Year)", heading_style))
        
        lt_data = [['Asset', 'Date Acquired', 'Date Sold', 'Proceeds', 'Cost Basis', 'Gain/Loss']]
        
        for gain in summary_data['realized_gains']:
            if gain['term'] == 'long-term':
                lt_data.append([
                    gain['symbol'],
                    gain['date_acquired'].strftime('%m/%d/%Y'),
                    gain['date_sold'].strftime('%m/%d/%Y'),
                    f"${gain['proceeds']:,.2f}",
                    f"${gain['cost_basis']:,.2f}",
                    f"${gain['gain_loss']:,.2f}"
                ])
        
        lt_table = Table(lt_data, colWidths=[0.8*inch, 1.2*inch, 1.2*inch, 1.3*inch, 1.3*inch, 1.2*inch])
        lt_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#27ae60')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (3, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
        ]))
        
        elements.append(lt_table)
        elements.append(Spacer(1, 0.3*inch))
    
    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#888888'),
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique'
    )
    
    elements.append(Spacer(1, 0.5*inch))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')} | CryptoTax Micro v1.0",
        footer_style
    ))
    
    # Build PDF
    doc.build(elements)
    
    return output_path


if __name__ == "__main__":
    # Test PDF generation
    from tax_calculator import TaxCalculator, Transaction
    
    calc = TaxCalculator(method='FIFO')
    calc.add_transaction(Transaction('2023-01-15', 'buy', 1.0, 20000, 'BTC', 10))
    calc.add_transaction(Transaction('2023-06-20', 'buy', 0.5, 30000, 'BTC', 5))
    calc.add_transaction(Transaction('2024-01-10', 'sell', 1.2, 45000, 'BTC', 20))
    
    summary = calc.generate_summary()
    generate_pdf_report(summary, 'test_report.pdf')
    print("✅ Test PDF generated: test_report.pdf")
